// flow-typed signature: 2e9917af482e5f60238ba8c2a7cbbc98
// flow-typed version: <<STUB>>/gatsby-plugin-image_v^2.16.1/flow_v0.180.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-image/dist/babel-helpers' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/babel-plugin-parse-static-images' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/gatsby-image.browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/gatsby-image.server' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/hooks' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/intersection-observer' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/layout-wrapper' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/lazy-hydrate' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/main-image' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/picture' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/placeholder' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/components/static-image.server' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/gatsby-image.browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/gatsby-image.browser.modern' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/gatsby-image' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/gatsby-image.module' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/global' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/image-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/index.browser-1e6cf5a9' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/index.browser-4760edcd' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/lazy-hydrate-64ce7b2b' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/lazy-hydrate-6766eb3d' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/node-apis/image-processing' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/node-apis/node-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/node-apis/parser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/node-apis/preprocess-source' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/node-apis/watcher' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/dist/resolver-utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/gatsby-ssr' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-image/graphql-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-image/dist/babel-helpers.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/babel-helpers'>;
}
declare module 'gatsby-plugin-image/dist/babel-plugin-parse-static-images.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/babel-plugin-parse-static-images'>;
}
declare module 'gatsby-plugin-image/dist/components/gatsby-image.browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/gatsby-image.browser'>;
}
declare module 'gatsby-plugin-image/dist/components/gatsby-image.server.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/gatsby-image.server'>;
}
declare module 'gatsby-plugin-image/dist/components/hooks.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/hooks'>;
}
declare module 'gatsby-plugin-image/dist/components/intersection-observer.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/intersection-observer'>;
}
declare module 'gatsby-plugin-image/dist/components/layout-wrapper.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/layout-wrapper'>;
}
declare module 'gatsby-plugin-image/dist/components/lazy-hydrate.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/lazy-hydrate'>;
}
declare module 'gatsby-plugin-image/dist/components/main-image.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/main-image'>;
}
declare module 'gatsby-plugin-image/dist/components/picture.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/picture'>;
}
declare module 'gatsby-plugin-image/dist/components/placeholder.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/placeholder'>;
}
declare module 'gatsby-plugin-image/dist/components/static-image.server.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/components/static-image.server'>;
}
declare module 'gatsby-plugin-image/dist/gatsby-image.browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/gatsby-image.browser'>;
}
declare module 'gatsby-plugin-image/dist/gatsby-image.browser.modern.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/gatsby-image.browser.modern'>;
}
declare module 'gatsby-plugin-image/dist/gatsby-image.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/gatsby-image'>;
}
declare module 'gatsby-plugin-image/dist/gatsby-image.module.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/gatsby-image.module'>;
}
declare module 'gatsby-plugin-image/dist/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/gatsby-node'>;
}
declare module 'gatsby-plugin-image/dist/global.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/global'>;
}
declare module 'gatsby-plugin-image/dist/image-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/image-utils'>;
}
declare module 'gatsby-plugin-image/dist/index.browser-1e6cf5a9.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/index.browser-1e6cf5a9'>;
}
declare module 'gatsby-plugin-image/dist/index.browser-4760edcd.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/index.browser-4760edcd'>;
}
declare module 'gatsby-plugin-image/dist/index' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist'>;
}
declare module 'gatsby-plugin-image/dist/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist'>;
}
declare module 'gatsby-plugin-image/dist/lazy-hydrate-64ce7b2b.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/lazy-hydrate-64ce7b2b'>;
}
declare module 'gatsby-plugin-image/dist/lazy-hydrate-6766eb3d.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/lazy-hydrate-6766eb3d'>;
}
declare module 'gatsby-plugin-image/dist/node-apis/image-processing.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/node-apis/image-processing'>;
}
declare module 'gatsby-plugin-image/dist/node-apis/node-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/node-apis/node-utils'>;
}
declare module 'gatsby-plugin-image/dist/node-apis/parser.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/node-apis/parser'>;
}
declare module 'gatsby-plugin-image/dist/node-apis/preprocess-source.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/node-apis/preprocess-source'>;
}
declare module 'gatsby-plugin-image/dist/node-apis/watcher.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/node-apis/watcher'>;
}
declare module 'gatsby-plugin-image/dist/resolver-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/dist/resolver-utils'>;
}
declare module 'gatsby-plugin-image/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/gatsby-node'>;
}
declare module 'gatsby-plugin-image/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/gatsby-ssr'>;
}
declare module 'gatsby-plugin-image/graphql-utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-image/graphql-utils'>;
}
