// flow-typed signature: 63bfc46bc2790c98122ab7d2cf598610
// flow-typed version: <<STUB>>/gatsby-transformer-sharp_v^4.9.0/flow_v0.173.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-sharp/create-resolvers' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/customize-schema' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/error-utils' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/on-node-create' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/safe-sharp' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/create-resolvers' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/customize-schema' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/error-utils' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/fragments' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/on-node-create' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/safe-sharp' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/src/supported-extensions' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/supported-extensions' {
  declare module.exports: any;
}

declare module 'gatsby-transformer-sharp/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-sharp/create-resolvers.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/create-resolvers'>;
}
declare module 'gatsby-transformer-sharp/customize-schema.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/customize-schema'>;
}
declare module 'gatsby-transformer-sharp/error-utils.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/error-utils'>;
}
declare module 'gatsby-transformer-sharp/fragments.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/fragments'>;
}
declare module 'gatsby-transformer-sharp/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/gatsby-node'>;
}
declare module 'gatsby-transformer-sharp/index' {
  declare module.exports: $Exports<'gatsby-transformer-sharp'>;
}
declare module 'gatsby-transformer-sharp/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp'>;
}
declare module 'gatsby-transformer-sharp/on-node-create.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/on-node-create'>;
}
declare module 'gatsby-transformer-sharp/safe-sharp.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/safe-sharp'>;
}
declare module 'gatsby-transformer-sharp/src/create-resolvers.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/create-resolvers'>;
}
declare module 'gatsby-transformer-sharp/src/customize-schema.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/customize-schema'>;
}
declare module 'gatsby-transformer-sharp/src/error-utils.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/error-utils'>;
}
declare module 'gatsby-transformer-sharp/src/fragments.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/fragments'>;
}
declare module 'gatsby-transformer-sharp/src/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/gatsby-node'>;
}
declare module 'gatsby-transformer-sharp/src/on-node-create.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/on-node-create'>;
}
declare module 'gatsby-transformer-sharp/src/safe-sharp.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/safe-sharp'>;
}
declare module 'gatsby-transformer-sharp/src/supported-extensions.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/src/supported-extensions'>;
}
declare module 'gatsby-transformer-sharp/supported-extensions.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/supported-extensions'>;
}
declare module 'gatsby-transformer-sharp/types.js' {
  declare module.exports: $Exports<'gatsby-transformer-sharp/types'>;
}
