// flow-typed signature: 4abbdf52da955e04405b80744df5da6b
// flow-typed version: <<STUB>>/gatsby-plugin-typegen_vportal:../../plugin/flow_v0.180.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-typegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-typegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-typegen/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/config' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/machine' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/machine.typegen' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/pluginOptions' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/reporter' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/internal/utils' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/services/autofix' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/services/codegen' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/services/emitPluginDocument' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/services/emitSchema' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/src/types.flow' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/types.flow' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/types' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/typing/gatsby.d' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-typegen/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-typegen/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/gatsby-node'>;
}
declare module 'gatsby-plugin-typegen/index' {
  declare module.exports: $Exports<'gatsby-plugin-typegen'>;
}
declare module 'gatsby-plugin-typegen/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen'>;
}
declare module 'gatsby-plugin-typegen/internal/config.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/config'>;
}
declare module 'gatsby-plugin-typegen/internal/machine.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/machine'>;
}
declare module 'gatsby-plugin-typegen/internal/machine.typegen.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/machine.typegen'>;
}
declare module 'gatsby-plugin-typegen/internal/pluginOptions.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/pluginOptions'>;
}
declare module 'gatsby-plugin-typegen/internal/reporter.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/reporter'>;
}
declare module 'gatsby-plugin-typegen/internal/utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/internal/utils'>;
}
declare module 'gatsby-plugin-typegen/services/autofix.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/services/autofix'>;
}
declare module 'gatsby-plugin-typegen/services/codegen.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/services/codegen'>;
}
declare module 'gatsby-plugin-typegen/services/emitPluginDocument.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/services/emitPluginDocument'>;
}
declare module 'gatsby-plugin-typegen/services/emitSchema.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/services/emitSchema'>;
}
declare module 'gatsby-plugin-typegen/src/types.flow.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/src/types.flow'>;
}
declare module 'gatsby-plugin-typegen/types.flow.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/types.flow'>;
}
declare module 'gatsby-plugin-typegen/types.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/types'>;
}
declare module 'gatsby-plugin-typegen/typing/gatsby.d.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/typing/gatsby.d'>;
}
declare module 'gatsby-plugin-typegen/utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-typegen/utils'>;
}
