// flow-typed signature: 6070ea22703aa714c52086406ddc54a3
// flow-typed version: <<STUB>>/gatsby-plugin-react-helmet-async_v^1.2.1/flow_v0.173.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-react-helmet-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-react-helmet-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-react-helmet-async/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-react-helmet-async/gatsby-ssr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-react-helmet-async/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet-async/gatsby-browser'>;
}
declare module 'gatsby-plugin-react-helmet-async/gatsby-ssr.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet-async/gatsby-ssr'>;
}
declare module 'gatsby-plugin-react-helmet-async/index' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet-async'>;
}
declare module 'gatsby-plugin-react-helmet-async/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-react-helmet-async'>;
}
