// flow-typed signature: 4e938ca9aac2c711170f43ae7f91c82d
// flow-typed version: <<STUB>>/gatsby-plugin-sharp_v^4.16.1/flow_v0.180.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-sharp/duotone' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/gatsby-worker' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/image-data' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/plugin-options' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/process-file' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/report-error' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/safe-sharp.d' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/safe-sharp' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/sharp-error' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/trace-svg' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-sharp/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-sharp/duotone.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/duotone'>;
}
declare module 'gatsby-plugin-sharp/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/gatsby-node'>;
}
declare module 'gatsby-plugin-sharp/gatsby-worker.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/gatsby-worker'>;
}
declare module 'gatsby-plugin-sharp/image-data.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/image-data'>;
}
declare module 'gatsby-plugin-sharp/index' {
  declare module.exports: $Exports<'gatsby-plugin-sharp'>;
}
declare module 'gatsby-plugin-sharp/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp'>;
}
declare module 'gatsby-plugin-sharp/plugin-options.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/plugin-options'>;
}
declare module 'gatsby-plugin-sharp/process-file.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/process-file'>;
}
declare module 'gatsby-plugin-sharp/report-error.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/report-error'>;
}
declare module 'gatsby-plugin-sharp/safe-sharp.d.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/safe-sharp.d'>;
}
declare module 'gatsby-plugin-sharp/safe-sharp.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/safe-sharp'>;
}
declare module 'gatsby-plugin-sharp/sharp-error.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/sharp-error'>;
}
declare module 'gatsby-plugin-sharp/trace-svg.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/trace-svg'>;
}
declare module 'gatsby-plugin-sharp/utils.js' {
  declare module.exports: $Exports<'gatsby-plugin-sharp/utils'>;
}
