// flow-typed signature: 13f1372ccbeb567d520f5ff37b24e815
// flow-typed version: <<STUB>>/react-helmet-async_v^1.2.3/flow_v0.173.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet-async/lib' {
  declare module.exports: any;
}

declare module 'react-helmet-async/lib/index.modern' {
  declare module.exports: any;
}

declare module 'react-helmet-async/lib/index.module' {
  declare module.exports: any;
}

declare module 'react-helmet-async/lib/index.umd' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/client' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/constants' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/Dispatcher' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/HelmetData' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/Provider' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/server' {
  declare module.exports: any;
}

declare module 'react-helmet-async/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet-async/lib/index' {
  declare module.exports: $Exports<'react-helmet-async/lib'>;
}
declare module 'react-helmet-async/lib/index.js' {
  declare module.exports: $Exports<'react-helmet-async/lib'>;
}
declare module 'react-helmet-async/lib/index.modern.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/index.modern'>;
}
declare module 'react-helmet-async/lib/index.module.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/index.module'>;
}
declare module 'react-helmet-async/lib/index.umd.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/index.umd'>;
}
declare module 'react-helmet-async/src/client.js' {
  declare module.exports: $Exports<'react-helmet-async/src/client'>;
}
declare module 'react-helmet-async/src/constants.js' {
  declare module.exports: $Exports<'react-helmet-async/src/constants'>;
}
declare module 'react-helmet-async/src/Dispatcher.js' {
  declare module.exports: $Exports<'react-helmet-async/src/Dispatcher'>;
}
declare module 'react-helmet-async/src/HelmetData.js' {
  declare module.exports: $Exports<'react-helmet-async/src/HelmetData'>;
}
declare module 'react-helmet-async/src/index' {
  declare module.exports: $Exports<'react-helmet-async/src'>;
}
declare module 'react-helmet-async/src/index.js' {
  declare module.exports: $Exports<'react-helmet-async/src'>;
}
declare module 'react-helmet-async/src/Provider.js' {
  declare module.exports: $Exports<'react-helmet-async/src/Provider'>;
}
declare module 'react-helmet-async/src/server.js' {
  declare module.exports: $Exports<'react-helmet-async/src/server'>;
}
declare module 'react-helmet-async/src/utils.js' {
  declare module.exports: $Exports<'react-helmet-async/src/utils'>;
}
