plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

nmMode: hardlinks-global
nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@xstate/tools-shared@*":
    dependencies:
      "prettier": "*"
  "@xstate/machine-extractor@*":
    dependencies:
      "@babel/core": "*"
