nmMode: hardlinks-global

nodeLinker: node-modules

packageExtensions:
  "@xstate/machine-extractor@*":
    dependencies:
      "@babel/core": "*"
  "@xstate/tools-shared@*":
    dependencies:
      prettier: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
