plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

nmMode: hardlinks-global
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@xstate/tools-shared@*":
    dependencies:
      "prettier": "*"
  "@xstate/machine-extractor@*":
    dependencies:
      "@babel/core": "*"
