plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-bump.js
    spec: "https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.6/plugin-bump.js"

yarnPath: .yarn/releases/yarn-berry.js
